# Generated by Django 4.2 on 2024-06-25 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrole',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_role', to=settings.AUTH_USER_MODEL),
        ),
    ]
