# Generated by Django 4.2 on 2024-06-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_account_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
