# Generated by Django 4.2 on 2024-06-04 13:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_nakit', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('comission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reservation_date', models.DateField(default=datetime.date(2024, 6, 4))),
                ('transfer_type', models.CharField(choices=[('ARR', 'Arrival'), ('DEP', 'Departure'), ('ARA', 'Ara Transfer'), ('TUR', 'Tur')], default='ARR', max_length=50)),
                ('transfer_date', models.DateField(default=datetime.date(2024, 6, 4))),
                ('transfer_time', models.CharField(max_length=25)),
                ('flight_number', models.CharField(max_length=25)),
                ('passenger_name', models.CharField(max_length=255)),
                ('passenger_count', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, null=True)),
                ('pickup_short', models.CharField(max_length=255)),
                ('pickup_full', models.CharField(max_length=1024)),
                ('dest_short', models.CharField(max_length=255)),
                ('dest_full', models.CharField(max_length=1024)),
                ('is_my_driver', models.BooleanField(default=True)),
                ('taseron_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.agency')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.car')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.cartype')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.currency')),
                ('my_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.driver')),
                ('taseron', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='partner.taseron')),
                ('taseron_currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='taseron_currency', to='company.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='company.currency')),
            ],
        ),
    ]
