# Generated by Django 4.2 on 2024-06-05 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_reservation_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='comission',
            new_name='agency_comission',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='taseron_amount',
            new_name='taseron_hakedis',
        ),
    ]
